//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MC.Code.CLI.Command.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationCommandRunner {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationCommandRunner() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MC.Code.CLI.Command.Resources.ApplicationCommandRunner", typeof(ApplicationCommandRunner).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command execution error: {0}.
        /// </summary>
        internal static string CommandExecutionError {
            get {
                return ResourceManager.GetString("CommandExecutionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0}\nexpected parameter %{1} ({2}) type {3}.
        /// </summary>
        internal static string ConversionError {
            get {
                return ResourceManager.GetString("ConversionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion of the CLI value to type {0} is not supported..
        /// </summary>
        internal static string ConversionNotSupported {
            get {
                return ResourceManager.GetString("ConversionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element &apos;{0}&apos; has an invalid index {1}..
        /// </summary>
        internal static string InvalidParameterIndex {
            get {
                return ResourceManager.GetString("InvalidParameterIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required parameter: {0}.
        /// </summary>
        internal static string MissingRequiredParameter {
            get {
                return ResourceManager.GetString("MissingRequiredParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option name/alias &apos;{0}&apos; has been defined more than once..
        /// </summary>
        internal static string OptionAliasDefinedMoreThanOnce {
            get {
                return ResourceManager.GetString("OptionAliasDefinedMoreThanOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option {0} has an invalid type. {1}. Allowed type: System.Boolean. Opcja {0} ma nieprawidłowy typ. {1}. Dozwolony typ: System.Boolean..
        /// </summary>
        internal static string OptionBooleanRequired {
            get {
                return ResourceManager.GetString("OptionBooleanRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option &apos;{0}&apos; has been defined more than once..
        /// </summary>
        internal static string OptionDefinedMoreThanOnce {
            get {
                return ResourceManager.GetString("OptionDefinedMoreThanOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option {0} has an invalid type. {1}. For multiple definitions of ApplicationOptionAttribute an enum is required..
        /// </summary>
        internal static string OptionInvalidType {
            get {
                return ResourceManager.GetString("OptionInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following options cannot be used simultaneously: {0}. The options apply to the same parameter..
        /// </summary>
        internal static string OptionsCannotBeUsedSimultaneously {
            get {
                return ResourceManager.GetString("OptionsCannotBeUsedSimultaneously", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options belonging to parameter {0} have different types: {1} and {2}..
        /// </summary>
        internal static string OptionsDifferentTypes {
            get {
                return ResourceManager.GetString("OptionsDifferentTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The option &apos;{0}&apos; was specified more than once..
        /// </summary>
        internal static string OptionSpecifiedMoreThanOnce {
            get {
                return ResourceManager.GetString("OptionSpecifiedMoreThanOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; ({1}) was simultaneously defined as ApplicationParameter and ApplicationOption..
        /// </summary>
        internal static string ParameterAndOptionConflict {
            get {
                return ResourceManager.GetString("ParameterAndOptionConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; remained defined as ApplicationParameter more than once..
        /// </summary>
        internal static string ParameterDefinedMoreThanOnce {
            get {
                return ResourceManager.GetString("ParameterDefinedMoreThanOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter error: {0}.
        /// </summary>
        internal static string ParameterError {
            get {
                return ResourceManager.GetString("ParameterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; ({1}) has more than one role..
        /// </summary>
        internal static string ParameterMultipleRoles {
            get {
                return ResourceManager.GetString("ParameterMultipleRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; ({1}) has no defined role..
        /// </summary>
        internal static string ParameterNoRole {
            get {
                return ResourceManager.GetString("ParameterNoRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; ({1}) has type {2}, but ApplicationParameter declares type {3}..
        /// </summary>
        internal static string ParameterTypeMismatch {
            get {
                return ResourceManager.GetString("ParameterTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Unknown command: {0}.
        /// </summary>
        internal static string UnknownCommand {
            get {
                return ResourceManager.GetString("UnknownCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Unknown option: {0}.
        /// </summary>
        internal static string UnknownOption {
            get {
                return ResourceManager.GetString("UnknownOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Unknown property: {0}.
        /// </summary>
        internal static string UnknownProperty {
            get {
                return ResourceManager.GetString("UnknownProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; cannot be converted to type {1}..
        /// </summary>
        internal static string ValueCannotConvert {
            get {
                return ResourceManager.GetString("ValueCannotConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is not a single character..
        /// </summary>
        internal static string ValueNotSingleCharacter {
            get {
                return ResourceManager.GetString("ValueNotSingleCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is not a valid boolean value..
        /// </summary>
        internal static string ValueNotValidBoolean {
            get {
                return ResourceManager.GetString("ValueNotValidBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The value &apos;{0}&apos; is not a valid value of type {1}..
        /// </summary>
        internal static string ValueNotValidEnum {
            get {
                return ResourceManager.GetString("ValueNotValidEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is not a valid GUID..
        /// </summary>
        internal static string ValueNotValidGuid {
            get {
                return ResourceManager.GetString("ValueNotValidGuid", resourceCulture);
            }
        }
    }
}
